version: '3.7'
services:
  sick-tracker:
    image: localhost:5000/sick-tracker:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '1G'
        reservations:
          memory: '1G'
      restart_policy:
        condition: on-failure